apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: gohello 
  labels:
    app: gohello
spec:
  replicas: 1 
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-test
  template:
    spec:
      containers:
        - name: gohello 
          image: registry.cn-hangzhou.aliyuncs.com/svipdp/gohttphello:v3
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 38080
              hostPort: 38080

