kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: heketi-gluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit 
subjects:
- kind: ServiceAccount
  name: heketi-service-account 
  namespace: default 

