---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: heketi-sa
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: heketi-gluster-admin
subjects:
- kind: ServiceAccount
  name: heketi-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit 
