apiVersion: v1
kind: ConfigMap
metadata:
  name: heketi-topology
  namespace: {{ .Release.Namespace }} 
data:
  topology.yaml: |-
    {
      "clusters": [
        {
          "nodes": [
            {
              "node": {
                "hostnames": {
                  "manage": [
                    "node1"
                  ],
                  "storage": [
                    "192.168.1.1"
                  ]
                },
                "zone": 1
              },
              "devices": [
                "/dev/sda3"
              ]
            },
            {
              "node": {
                "hostnames": {
                  "manage": [
                    "node2"
                  ],
                  "storage": [
                    "192.168.1.2"
                  ]
                },
                "zone": 1
              },
              "devices": [
                "/dev/sda3"
              ]
            },
            {
              "node": {
                "hostnames": {
                  "manage": [
                    "node3"
                  ],
                  "storage": [
                    "192.168.1.3"
                  ]
                },
                "zone": 1
              },
              "devices": [
                "/dev/sda3"
              ]
            }
          ]
        }
      ]
    }

